interaction_homepage:
    path:     /recherche
    defaults: { _controller: InteractionBundle:Recherche:recherche }

search_result:
    path:     /getresult
    defaults: { _controller: InteractionBundle:Recherche:resultat }

message_data:
    path:     /getmessages
    defaults: { _controller: InteractionBundle:Message:getMessages }

send_message:
    path:     /sendmessage
    defaults: { _controller: InteractionBundle:Message:sendMessage }
