main_homepage:
    path:     /
    defaults: { _controller: MainBundle:Default:index }

loginadmin:
    path:     /loginadmin
    defaults: { _controller: MainBundle:AdminSecurity:login }

admin:
    path:     /admin
    defaults: { _controller: MainBundle:AdminSecurity:admin }
test:
    path:     /test
    defaults: { _controller: MainBundle:Main:test }
