main_homepage:
    path:     /
    defaults: { _controller: MainBundle:Default:index }

loginadmin:
    path:     /loginadmin
    defaults: { _controller: MainBundle:AdminSecurity:login }

admin:
    path:     /admin
    defaults: { _controller: MainBundle:AdminSecurity:admin }

indexAdmin:
    path:     /admin/profiladmin
    defaults: { _controller: MainBundle:ProfilAdmin:index }

usersAdmin:
    path:     /admin/profiladmin/users
    defaults: { _controller: MainBundle:ProfilAdmin:utilisateurs }

statAdmin:
    path:     /admin/profiladmin/statistiques
    defaults: { _controller: MainBundle:ProfilAdmin:statProfil }

signalAdmin:
    path:     /admin/profiladmin/signaled
    defaults: { _controller: MainBundle:ProfilAdmin:utilisateurSignal }

statistique_recherche_generale:
    path:     /admin/recherchestatg
    defaults: { _controller: MainBundle:StatistiqueRecherche:generale }

